version: '2'
services:
#  nginx:
#    image: nginx
#    volumes:
#      - coffeeapp_coffee_docs_vol:/usr/share/nginx/html/coffee_docs
#    ports:
#      - 8081:80
  coffeeapp:
    image: coffeeapp:4
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coffee
      SPRING_DATASOURCE_USERNAME: coffee
      SPRING_DATASOURCE_PASSWORD: coffee
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - coffeeapp_coffee_docs_vol:/root/coffee_docs
#      - ./coffee_docs:/root/coffee_docs
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: coffee
      POSTGRES_PASSWORD: coffee
      POSTGRES_DB: coffee
volumes:
  coffeeapp_coffee_docs_vol:
